// FAIL
// Using it outside of loop 2

fn main() -> int {

    while (true) {
        out it;
    }

}